// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvmcamqmoantldxeqbrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bWNhbXFtb2FudGxkeGVxYnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTMwNDQsImV4cCI6MjA2MzM4OTA0NH0.gkoN-Ycw9wh2JeM6cc6g1sYStQyAQJ6yBIaWjcZoKEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);